name: Build and push docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TAG: 0.31.14

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build project image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            verdel/plex-trakt-sync:latest
            verdel/plex-trakt-sync:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download personal actions
        uses: actions/checkout@v4
        with:
          repository: verdel/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions
        if: always()

      - name: Send message on success
        uses: ./actions/telegram-send-message/v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          recipient: ${{ secrets.TELEGRAM_RECIPIENTS }}
          message: "Docker image verdel/plex-trakt-sync:${{ env.TAG }} build success"
        if: success()

      - name: Send message on failure
        uses: ./actions/telegram-send-message/v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          recipient: ${{ secrets.TELEGRAM_RECIPIENTS }}
          message: "Docker image verdel/plex-trakt-sync:${{ env.TAG }} build failure"
        if: failure()
