name: Test build docker image
on:
  push:
    branches-ignore:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build project image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            verdel/plex-trakt-sync:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
